### ISSUE TITLE
Fix logo logic

### ISSUE THREAD

**Issue by carrieforde** [carrieforde/Alcatraz#26]
Currently, our logo only shows in both mobile and desktop views if there is both a mobile and desktop logo. Ideally, we need some sort of check that says if the user only uploads on logo, then use that logo for both the mobile and desktop.

**Comment by jgonzo127** [comment]
We now have a "has-mobile-logo" class when a mobile logo is uploaded. We can now hide the desktop logo when this class is present, otherwise we will just default to desktop logo.

**Comment by carrieforde** [comment]
Fixed by e756ae44dbd3ed02b08a7afc653601f0c80677b5 and ff785235bf2cc85bd08c41f2478903ea72a6e33c.
