### ISSUE TITLE
Find a better way to hide "Toggle" on mobile menu triggers

### ISSUE THREAD

**Issue by carrieforde** [carrieforde/Alcatraz#47]
Currently, the word "Toggle" is hidden with a transparent color, but we may want to consider alternate solutions, like `opacity: 0;` or anything mentioned in this article on CSS Tricks: [Toggle Visibility When Hiding Elements](https://css-tricks.com/snippets/css/toggle-visibility-when-hiding-elements/).

**Comment by BraadMartin** [comment]
We have a mixin @hide-text that looks like it does a nice job. Here it is in use on the Hamburger mobile nav toggle:

```
.mobile-nav-toggle-style-hamburger .menu-toggle .menu-text {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}
```

Personally I like text-indent, but whatever works across all browsers is fine.

**Comment by carrieforde** [comment]
The problem with `@include hide-text;` and `opacity: 0;` was that they also hid the sub-menu toggles (plus/minus or chevron). Text indent did a lovely job in this case.
