### ISSUE TITLE
Let's change Vendor to Plugins in our Scss file

### ISSUE THREAD

**Issue by BraadMartin** [carrieforde/Alcatraz#7]
Feel free to close this if you disagree, but to me Plugins sounds better, and all of the sub sections will be plugin names rather than the names of the companies making the plugins.

https://github.com/carrieforde/Alcatraz/blob/master/sass/style.scss#L76

**Comment by carrieforde** [comment]
Done. I tried to think of a use case for anything that wasn't plugins, but couldn't think of anything at the minute.

Fixed with 55a4562e9957fed2f718ebdf7674afd5a5bda35d.
