### ISSUE TITLE
Use npm to add Bourbon & Neat

### ISSUE THREAD

**Issue by carrieforde** [carrieforde/Alcatraz#82]
We can streamline the installation process by requiring Bourbon and Neat through npm instead of Bower. That way, devs and new users can simply run `npm install` instead of `npm install && bower install`.

https://github.com/thoughtbot/bourbon#installing-with-npm-and-using-a-node-based-asset-pipeline

https://github.com/thoughtbot/neat#installing-with-npm-and-using-a-node-based-asset-pipeline

**Comment by BraadMartin** [comment]
:+1: NPM for all the things. RIP Bower.
