### ISSUE TITLE
Remove Media Query Sass Variables

### ISSUE THREAD

**Issue by BraadMartin** [carrieforde/Alcatraz#9]
I saw that the breakpoints have been updated, and I think we need further discussion.

First for reference, here is what I had proposed:
`$breakpoint__mobile-small: 360px;`
`$breakpoint__mobile: 480px;`
`$breakpoint__mobile-large: 600px;`
`$breakpoint__tablet: 768px;`
`$breakpoint__tablet-large: 900px;`
`$breakpoint__desktop: 1024px;`
`$breakpoint__desktop-large: 1440px;`

And here is what Carrie has proposed:
`$breakpoint__mobile-phone: "(min-width: 400px)";`
`$breakpoint__small-tablet: "(min-width: 540px)";`
`$breakpoint__tablet: "(min-width: 768px)";`
`$breakpoint__desktop: "(min-width: 960px)";`
`$breakpoint__desktop-large: "(min-width: 1200px)";`

The breakpoints that I chose were based on common device widths or they were ones that I've found critical to have as I've built many, many mobile-first websites. Here is a good list of common device widths for reference: http://mydevice.io/devices/

For example, 320px is the narrowest width that I usually care about supporting, because that is the width of the first iPhone. But now many mobile phones are 360px or 380px, and I think optimizing between 320-400px is critical to getting great mobile phone browsing experiences, so having a breakpoint at 360px is something I've had in almost every site I've developed for a while. In your case I think the spread between 320px and 400px is too big, and if you check the mydevice.io list you'll see that almost all of the common phones start at less than 400px, so without a breakpoint below 400px we have no way of distinguishing between the tiny 320px screens and the more common 360-380px screens.

As another example, 540px doesn't correspond to any common screen size that I can find. The older iPhones in landscape are 480px, and most newer devices are 640px. I've often found the gap between 480 and 640 to be too big, and also I don't usually make a lot of changes between 640 and 768, and there are some smaller tablets that start at 600, so that is why I usually end up with a breakpoint at 600px, but I'd support both 480px and 640px or 480px and 600px over a single breakpoint at 540px.

Another example, 960px isn't bad, but I think 1024px is a must because that is the landscape width of iPads and a pretty big list of other devices. Because 960 and 1024 are so close together, I usually end with a breakpoint at 900px, because to me that feels like a nice even split between 768 and 1024.

The 1200px breakpoint makes for nice math, but it also doesn't correspond to any known device sizes that I can find. I see 1024, 1280, and 1440 as the common device sizes in the range, and to me 1024 and above is desktop, so I consider 1024 and 1440 to be the most useful breakpoints in this range.

I also don't like the inconsistency of naming between `desktop-large` and `small-tablet`. If we stick with `small-tablet`, I think it should be renamed `tablet-small`, but actually, I can't find a single common tablet that has a screen width of 540px, so maybe the breakpoint in this range should be `mobile-large`.

Along similar lines, I also think `mobile-phone` as a breakpoint name isn't ideal. iPods have mobile browsers these days but they aren't considered phones. I think our three main breakpoint identifiers should be `mobile`, `tablet`, and `desktop`, and all of our sub-sizes based off these should be `-large` or `-small`.

Finally, I don't like that we're wrapping up the min-width statement with these variables. Yes, we're building a mobile first theme here, but that doesn't mean we can't include a max-width media query for certain things, and if we include the min-width statements in the variables then this isn't possible. An example of a max-width media query that I think makes sense is responsive table styling. If you try to use min-width queries to make tables responsive, you end up overwriting most of the browser's default table styling for mobile, then having to redefine all of the default table styling above mobile, leading to more code. This is why in Trestle, which is mobile-first, we use a max-width media query to include responsive table styling.

If we did want to create variables for the breakpoints that include min-width, I'd rather create extra $min-width-tablet variables that use the $breakpoint__tablet variables, that way we have easy access to both. I'm also realizing that we'll probably want to include our _variables.scss file in our child themes, and having these available outside of the min-width context would make much more sense there, as would having more breakpoints in general.

Let's continue this discussion and see if we can come to a consensus. I'm open to changes to the breakpoints that I proposed, but I want to see them backed up by some reasoning and use cases, similar to what I've laid out here. :)

**Comment by carrieforde** [comment]
Fair enough.

To be honest, I think adding in all these breakpoint variables is too much, too soon. We've barely written any Sass, so why do we need to define all these variables at this stage?

The breakpoints I added were based on the breakpoints of http://getskeleton.com/, upon which I loosely based my grid. In reality, I only needed one breakpoint at this stage.

Going forward, I'd like to follow the philosophy of [Stephen Hay](http://www.the-haystack.com/):

> Start with the small screen first, then expand until it looks like shit. Time for a breakpoint! 

So instead of laying out a fixed set of breakpoints right now, we should wait until we have a use-case for a breakpoint.. The grid, for example, is a perfect use-case.

Naming breakpoints seems completely arbitrary. I propose naming the breakpoint based on the screen's pixel width as so:
`$breakpoint__600px: 600px`

That gives the breakpoint more semantic meaning than `$breakpoint__mobile-small: 360px`, and it will also save our fingers a bit (especially since I now see your point about min vs max width queries).

I am also very interested in using ems instead of pixels as suggested by Brad Frost in his article, [7 Habits of Highly Effective Media Queries](http://bradfrost.com/blog/post/7-habits-of-highly-effective-media-queries/). It seems like a very smart solution for making a site more accessible for a visually impaired user, and I've found a great Sass function in Bourbon that can do the pixel-to-em calculation for us.

**Comment by BraadMartin** [comment]
The Brad Frost article is very interesting, and I agree with many of the points he makes and that you make. I'll respond to a few things specifically:

> We've barely written any Sass, so why do we need to define all these variables at this stage?

Agree.

> I propose naming the breakpoint based on the screen's pixel width as so: $breakpoint__600px: 600px

I don't like this. The advantage to naming them is that you can change the pixel values later, or convert to ems. Plus writing out `@media (min-width: $breakpoint__600px )` instead of `@media (min-width: 600px; )` just feels like unnecessary abstraction. The first habit in Brad Frost's article mentions that device sizes are always changing, well we can change with them by updating the value of these variables as devices get more high resolution if we name them.

> So instead of laying out a fixed set of breakpoints right now, we should wait until we have a use-case for a breakpoint.. The grid, for example, is a perfect use-case.

I agree, but I'm torn between 2 ideas:
1. We're laying out a set of choices that we'll be restricted to picking from in the future, which will keep our future code cleaner. If we define a great core set now then never again will we need to decide specific breakpoints again, and basing them off popular screen sizes is simply about optimizing for the majority of users.
2. If we were making a child theme for a specific site, of course we could and would let the content determine the breakpoints, but our theme doesn't have any content, and it doesn't know what the final content will be, so the breakpoints we need here are only really concerned with the layout of page sections and the grid system, so really we only need 2-3 breakpoints.

> I am also very interested in using ems instead of pixels as suggested by Brad Frost in his article, 7 Habits of Highly Effective Media Queries. It seems like a very smart solution for making a site more accessible for a visually impaired user, and I've found a great Sass function in Bourbon that can do the pixel-to-em calculation for us.

I'm intrigued by this. I haven't done it before, so it would be new territory, but I'm willing to try it. I do often zoom in on websites, and I don't experience the scroll bar he is talking about. For example, https://learn.generosity.com/learn/givingtuesday/ uses only pixel breakpoints, and for me in Chrome it not only zooms in but even though the screen is still big the mobile breakpoints eventually hit and you get a giant version of mobile. Same thing in Firefox. Maybe the need for ems used to be more of a thing and browsers have gotten better? I don't know, but I'd love to see an example where relative breakpoints would allow us to do something we couldn't do with pixel breakpoints. 

Based on this conversation, I say we strip out all of the media query variables now, and only add them back when it makes sense, but maybe we never add them back. I think it would be easy to define all grid related breakpoints in the _grid.scss file, same with the _navigation.scss file having the definition of the nav breakpoints, not as variables, but just as pixel or em values.

The more I think about it, the more I think there isn't even a need for breakpoint variables. I think I only added them because I was preoccupied with Sassing all the things and I was thinking about child theming. I'd support removing all of them for now.

**Comment by carrieforde** [comment]
Yeah, I was almost beginning to think the same thing as I was updating things. The advantage of keeping the breakpoints would be if we decide to use ems. Then we can use a Sass function to calculate them, and keep them in one place. Otherwise, I see little need.

**Comment by carrieforde** [comment]
I have completely removed the media query breakpoint variables from the Sass files. Going forward, I think it would be nice to use the Bourbon px-to-em function in our media queries, like so:

``` scss
@media (min-width: em(768)) {
    .something {
        ...
    }
}
```

Our em base on the body class is 16px. You can pass the em function a second variable which is your em-base if it's not the default, i.e. the parent container has an em base of 24:

``` scss
@media (min-width: em(768, 24)) {
    .something {
        ...
    }
}
```

I'm going to mark this closed now since I have removed the media query breakpoint variables.
